preload = ~/.config/hypr/bg/bg/IMG_2639.JPG
# .. more preloads

# set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper = ,~/.config/hypr/bg/bg/IMG_2639.JPG
# .. more monitors

# fully disable ipc
ipc = off

