"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[mgr]
show_hidden = false
show_symlink = true
linemode = "none"

[opener]
edit = [
    { run = 'kitty -T editor nvim "$@"', orphan = true, for = "unix" },
    { run = 'code "%*"', orphan = true, for = "windows" },
]
open = [
    { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
    { run = 'open "$@"', desc = "Open", for = "macos" },
    { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
extract = [
    { run = 'ark -d -a "$1"', desc = "Use ark to extract", for = "unix" },
    { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = 'mpv "%1"', orphan = true, for = "windows" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]
image = [{ run = 'imv "$@"', desc = "image viewer", for = "unix" }]
markdown = [
    { run = 'typora "$@"', orphan = true, desc = "markdown" },
    { run = 'kitty -T editor nvim "$@"', orphan = true, for = "unix" },
]
pdf = [
    { run = 'zathura "$@"', orphan = true, for = "unix", desc = "Zathura pdf viewer" },
    { run = 'google-chrome-stable --incognito "$@"', orphan = true, desc = "Open with Chrome in incognito mode" },
    { run = 'onlyoffice-desktopeditors "$@"', orphan = true, for = "unix", desc = "OnlyOffice pdf viewer" },
]
office = [
    { run = 'onlyoffice-desktopeditors "$@"', orphan = true, for = "unix", desc = "OnlyOffice" },
]

[open]
rules = [
    { name = "*.md", use = ["markdown"] },
    { name = "*.xls", use = ["office"] },
    { name = "*.xlsx", use = ["office"] },
    { name = "*.doc", use = ["office"] },
    { name = "*.docx", use = ["office"] },
    { name = "*.ppt", use = ["office"] },
    { name = "*.pptx", use = ["office"] },
    { name = "*.epub", use = ["pdf"] },
    { mime = "text/*", use = ["edit"] },
    { mime = "image/*", use = ["image", "open"] },
    { mime = "video/*", use = ["play"] },
    { mime = "audio/*", use = ["play"] },
    { name = "*.mp3", use = ["play"] },
    { name = "*.flac", use = ["play"] },
    { name = "*.ogg", use = ["play"] },
    { name = "*.wav", use = ["play"] },
    { mime = "inode/x-empty", use = ["edit"] },

    { mime = "application/json", use = ["edit"] },
    { mime = "*/javascript", use = ["edit"] },

    { mime = "application/zip", use = ["extract"] },
    { mime = "application/gzip", use = ["extract"] },
    { mime = "application/x-tar", use = ["extract"] },
    { mime = "application/x-bzip", use = ["extract"] },
    { mime = "application/x-bzip2", use = ["extract"] },
    { mime = "application/x-xz", use = ["extract"] },
    { name = "*.7z", use = ["extract"] },
    { name = "*.rar", use = ["extract"] },

    { mime = "application/pdf", use = ["pdf"] },
    { mime = "application/epub+zip", use = ["pdf"] },
]
