set -g mouse on
set -gq allow-passthrough on

set -g default-terminal "tmux-256color" # 解决 tmux 中无法使用 256 色的问题
set -ga terminal-overrides ",xterm-256color:Tc" # 全彩显示
set -as terminal-overrides ',xterm*:sitm=\E[3m' # 解决 Italic 字体无法显示的问题

set-option -s set-clipboard on
set-window-option -g mode-keys vi

set -g mode-style "fg=default,bg=default,reverse"
set -g status-bg color147
set -g status-fg white
set -g pane-border-style fg=default
set -ga pane-border-style bg=color147
set -g pane-active-border-style fg=black
set -ga pane-active-border-style bg=yellow
setw -g window-status-style fg=black
setw -g window-status-current-style fg=color160
setw -g window-status-activity-style fg=white
setw -g window-status-bell-style fg=white
set -g message-style bg=black,fg=orange

bind -n C-Left "resize-pane -L 5"
bind -n C-Right "resize-pane -R 5"
bind -n C-Up "resize-pane -U 5"
bind -n C-Down "resize-pane -D 5"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }
bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'


bind-key y copy-mode
bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "V" send -X rectangle-toggle
bind -T copy-mode-vi "y" send -X copy-selection

# move pane
bind-key ',' swap-pane -U # swap current pane with the one above it
bind-key '.' swap-pane -D # swap current pane with the one below it

# rename window
bind-key 'r' command-prompt -p "Rename window:" "rename-window '%%'"

bind-key R source-file ~/.config/tmux/tmux.conf \; display-message "configuration reloaded" # 重新加载 tmux 配置文件, 并显示提示信息
bind-key b last-window # 切换到上一个窗口

setw -g aggressive-resize on # 更主动地调整窗口大小以适应当前正在查看该窗口的客户端
set -g base-index 1 # 设置窗口索引从 1 开始
setw -g pane-base-index 1 # 设置窗格索引从 1 开始
set -g renumber-windows on # 当窗口关闭时, 重新编号其他窗口
set -g monitor-activity on # 非当前窗口有输出的时候, 提供提示
set -g history-limit 65536 # 增加历史记录限制, 以便在滚动时查看更多内容

set -sg escape-time 0 # 设置 tmux 的 escape 键超时时间为 0, 以便更快地响应按键事件, 特别是在使用 Vim 等需要快速按键的应用程序
set-option -g focus-events on # 允许 tmux 接收焦点事件, 以便在切换到 tmux 窗口时自动调整窗口大小

set -g status-interval 5 # 设置状态栏刷新间隔为 5 秒, 以便及时更新状态信息
set-option -g status-left '' # 状态栏左侧内容为空 (清空掉原来的`[0]`)
set -wg window-status-format "#I:#W#{?window_activity_flag,##,} " # 状态栏窗口名称格式
set -wg window-status-current-format "#I:#W#F " # 状态栏当前窗口名称格式(#I：序号，#w：窗口名称，#F：间隔符)
set -g window-status-activity-style "fg=white,bold" # 活动窗口样式
set -wg window-status-separator "" # 状态栏窗口名称之间的间隔
