#!/usr/bin/env bash

lock=swaylock
dimTime=580
lockTime=600
suspendTime=650
# dimTime=20
# lockTime=21
# suspendTime=22

kill -9 $(pidof swayidle) > /dev/null

while pgrep -x swayidle > /dev/null; do sleep 1; done

swayidle -w timeout 10 'if pgrep -x swaylock; then hyprctl dispatch dpms off > /dev/null; fi' resume 'echo resume; hyprctl dispatch dpms on > /dev/null' &

swayidle -w
    lock $lock \
    timeout $dimTime 'brightnessctl -s set 10' resume 'brightnessctl -r' \
    timeout $lockTime "pidof $lock || $lock" &
    # timeout $suspendTime 'hyprctl dispatch dpms on > /dev/null; sleep 1; echo suspend; systemctl suspend' \
