#!/bin/python

import datetime
import os

filename = str(datetime.datetime.now()).split(".")[0].replace(":", "-")
filename = f"Screenshot from {filename}.png"

size = os.popen("slurp", "r").read().replace("\n", "")

os.system(f'grim -g "{size}" ~/Pictures/Screenshots/"{filename}"')

os.system(f'xclip -sel clip -t image/png ~/Pictures/Screenshots/"{filename}"')
# os.system(f'wl-copy < ~/Pictures/"{filename}".png')

os.system("notify-send 截图一张")
