#!/bin/python

import datetime
import os

filename = str(datetime.datetime.now()).split(".")[0].replace(":", "-")
filename = f"Screenshot from {filename}.png"

size = os.popen("slurp", "r").read().replace("\n", "")

if size == "" or size is None:
    os.system("notify-send Cancel")
    exit()

status = os.system(f'grim -g "{size}" ~/Pictures/Screenshots/"{filename}"')

if status == 0:
    os.system(f'xclip -sel clip -t image/png ~/Pictures/Screenshots/"{filename}"')
    # os.system(f'wl-copy < ~/Pictures/"{filename}".png')
    os.system("notify-send Screen shot done!")
